<script src="https://giscus.app/client.js"
        data-repo="koenraijer/utterances"
        data-repo-id="R_kgDOHLAsiQ"
        data-category="Announcements"
        data-category-id="DIC_kwDOHLAsic4COjlc"
        data-mapping="pathname"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="preferred_color_scheme"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>